#!/usr/bin/env python3
"""
Script to split Summa Theologica text into individual article files
"""

import re
import os
import sys

def split_summa_text(input_file, output_dir):
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Split by articles using the pattern: "ARTICLE [NUMBER]" or "FIRST ARTICLE", "SECOND ARTICLE", etc.
    # The structure looks like: "FIRST ARTICLE [II-II, Q. 1, Art. 1]\n\nObjection 1:"
    article_pattern = r'(FIRST|SECOND|THIRD|FOURTH|FIFTH|SIXTH|SEVENTH|EIGHTH|NINTH|TENTH|ELEVENTH|TWELFTH|THIRTEENTH|FOURTEENTH|FIFTEENTH|SIXTEENTH|SEVENTEENTH|EIGHTEENTH|NINETEENTH|TWENTIETH|TWENTY-FIRST|TWENTY-SECOND|TWENTY-THIRD|TWENTY-FOURTH|TWENTY-FIFTH|TWENTY-SIXTH|TWENTY-SEVENTH|TWENTY-EIGHTH|TWENTY-NINTH|THIRTY-FIRST|THIRTY-SECOND|THIRTY-THIRD|THIRTY-FOURTH|THIRTY-FIFTH|THIRTY-SIXTH|THIRTY-SEVENTH|THIRTY-EIGHTH|THIRTY-NINTH|FORTY-FIRST|FORTY-SECOND|FORTY-THIRD|FORTY-FOURTH|FORTY-FIFTH|FORTY-SIXTH|FORTY-SEVENTH|FORTY-EIGHTH|FORTY-NINTH|FIFTY-FIRST|FIFTY-SECOND|FIFTY-THIRD|FIFTY-FOURTH|FIFTY-FIFTH|FIFTY-SIXTH|FIFTY-SEVENTH|FIFTY-EIGHTH|FIFTY-NINTH|SIXTY-FIRST|SIXTY-SECOND|SIXTY-THIRD|SIXTY-FOURTH|SIXTY-FIFTH|SIXTY-SIXTH|SIXTY-SEVENTH|SIXTY-EIGHTH|SIXTY-NINTH|SEVENTY-FIRST|SEVENTY-SECOND|SEVENTY-THIRD|SEVENTY-FOURTH|SEVENTY-FIFTH|SEVENTY-SIXTH|SEVENTY-SEVENTH|SEVENTY-EIGHTH|SEVENTY-NINTH|EIGHTY-FIRST|EIGHTY-SECOND|EIGHTY-THIRD|EIGHTY-FOURTH|EIGHTY-FIFTH|EIGHTY-SIXTH|EIGHTY-SEVENTH|EIGHTY-EIGHTH|EIGHTY-NINTH|NINETY-FIRST|NINETY-SECOND|NINETY-THIRD|NINETY-FOURTH|NINETY-FIFTH|NINETY-SIXTH|NINETY-SEVENTH|NINETY-EIGHTH|NINETY-NINTH|ONE HUNDREDTH|ONE HUNDRED AND FIRST|ONE HUNDRED AND SECOND|ONE HUNDRED AND THIRD|ONE HUNDRED AND FOURTH|ONE HUNDRED AND FIFTH|ONE HUNDRED AND SIXTH|ONE HUNDRED AND SEVENTH|ONE HUNDRED AND EIGHTH|ONE HUNDRED AND NINTH) ARTICLE \[([^\]]+)\]\s*\n\n(.*?)(?=(?:FIRST|SECOND|THIRD|FOURTH|FIFTH|SIXTH|SEVENTH|EIGHTH|NINTH|TENTH|ELEVENTH|TWELFTH|THIRTEENTH|FOURTEENTH|FIFTEENTH|SIXTEENTH|SEVENTEENTH|EIGHTEENTH|NINETEENTH|TWENTIETH|TWENTY-FIRST|TWENTY-SECOND|TWENTY-THIRD|TWENTY-FOURTH|TWENTY-FIFTH|TWENTY-SIXTH|TWENTY-SEVENTH|TWENTY-EIGHTH|TWENTY-NINTH|THIRTY-FIRST|THIRTY-SECOND|THIRTY-THIRD|THIRTY-FOURTH|THIRTY-FIFTH|THIRTY-SIXTH|THIRTY-SEVENTH|THIRTY-EIGHTH|THIRTY-NINTH|FORTY-FIRST|FORTY-SECOND|FORTY-THIRD|FORTY-FOURTH|FORTY-FIFTH|FORTY-SIXTH|FORTY-SEVENTH|FORTY-EIGHTH|FORTY-NINTH|FIFTY-FIRST|FIFTY-SECOND|FIFTY-THIRD|FIFTY-FOURTH|FIFTY-FIFTH|FIFTY-SIXTH|FIFTY-SEVENTH|FIFTY-EIGHTH|FIFTY-NINTH|SIXTY-FIRST|SIXTY-SECOND|SIXTY-THIRD|SIXTY-FOURTH|SIXTY-FIFTH|SIXTY-SIXTH|SIXTY-SEVENTH|SIXTY-EIGHTH|SIXTY-NINTH|SEVENTY-FIRST|SEVENTY-SECOND|SEVENTY-THIRD|SEVENTY-FOURTH|SEVENTY-FIFTH|SEVENTY-SIXTH|SEVENTY-SEVENTH|SEVENTY-EIGHTH|SEVENTY-NINTH|EIGHTY-FIRST|EIGHTY-SECOND|EIGHTY-THIRD|EIGHTY-FOURTH|EIGHTY-FIFTH|EIGHTY-SIXTH|EIGHTY-SEVENTH|EIGHTY-EIGHTH|EIGHTY-NINTH|NINETY-FIRST|NINETY-SECOND|NINETY-THIRD|NINETY-FOURTH|NINETY-FIFTH|NINETY-SIXTH|NINETY-SEVENTH|NINETY-EIGHTH|NINETY-NINTH|ONE HUNDREDTH|ONE HUNDRED AND FIRST|ONE HUNDRED AND SECOND|ONE HUNDRED AND THIRD|ONE HUNDRED AND FOURTH|ONE HUNDRED AND FIFTH|ONE HUNDRED AND SIXTH|ONE HUNDRED AND SEVENTH|ONE HUNDRED AND EIGHTH|ONE HUNDRED AND NINTH)\s+ARTICLE|\Z)'
    
    articles = re.findall(article_pattern, content, re.DOTALL)
    
    print(f"Found {len(articles)} articles")
    
    os.makedirs(output_dir, exist_ok=True)
    
    for i, article in enumerate(articles):
        # article[0] is the ordinal (FIRST, SECOND, etc.)
        # article[1] is the reference (II-II, Q. 1, Art. 1)
        # article[2] is the content
        
        title = f"{article[0]} ARTICLE [{article[1]}]"
        content_text = article[2].strip()
        
        # Clean up formatting
        content_text = re.sub(r'\r\n', '\n', content_text)
        content_text = re.sub(r'\n\s*\n\s*\n', '\n\n', content_text)
        
        if not content_text:
            continue
            
        # Create filename
        reference = article[1].replace('/', '_').replace(' ', '_')
        filename = f"article_{i+1:03d}_{reference}.txt"
        filepath = os.path.join(output_dir, filename)
        
        # Write the file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"{title}\n\n")
            f.write(content_text)
            
        print(f"Created: {filename}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python split_summa.py <input_file> <output_directory>")
        sys.exit(1)
        
    input_file = sys.argv[1]
    output_dir = sys.argv[2]
    
    split_summa_text(input_file, output_dir)